services:
  api:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./:/app
    networks:
      - text-evaluation-network

networks:
  text-evaluation-network:
    name: text-evaluation-network
    external: true
